---
- name: copy file over to flash on network device
  ansible.builtin.command: "scp -o StrictHostKeyChecking=no /tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt {{ ansible_user }}@{{ ansible_host }}:flash:{{ rollback_date }}-{{ inventory_hostname }}.txt"
  delegate_to: localhost

- name: overwrite startup config
  cisco.ios.ios_command:
    commands:
      - command: 'copy flash://{{ rollback_date }}-{{ inventory_hostname }}.txt startup-config'
        prompt:
          - Destination filename
        answer:
          - "\r"

- name: reboot machine
  cisco.ios.ios_command:
    commands:
      - command: 'reload'
        prompt:
          - Proceed
        answer:
          - "y"
  ignore_errors: true

- name: Wait for the network device to reload
  wait_for:
    host: "{{ ansible_host }}"
    delay: 40
    timeout: 600
    port: 22
  vars:
    ansible_connection: local

- name: reset the connection
  meta: reset_connection
