---
- name: clone github
  hosts: localhost
  gather_facts: false
  vars:
    root_path: /var/lib/ol-automation-manager/github
    token_github: github_vault
    repo_url: https://github.com/nhlongz/backups_config.git
  tasks:

    - name: Created backup path.
      file:
        path: "{{ root_path }}/backups_config"
        state: directory
      run_once: true
      delegate_to: localhost
    - name: Created backup_info folder
      file:
        path: "{{ root_path }}/config_change_info"
        state: directory
      run_once: true
      delegate_to: localhost

    - name: Clone and update github repo backup_config with branc main in /root_path.
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "/{{ root_path }}/backups_config"
        clone: yes
        update: yes
        single_branch: yes
        version: main
      run_once: true
      delegate_to: localhost
    - name: Clone and update github repo backup_config with branc config_change_info in /root_path/config_change_info
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "/{{ root_path }}/config_change_info"
        clone: yes
        update: yes
        single_branch: yes
        version: config_change_info
      run_once: true
      delegate_to: localhost