- name: retrieve network configurations
  hosts: localhost
  gather_facts: false
  vars:
    root_path: /var/lib/ol-automation-manager/github
  tasks:
    - name: git push
      shell: |
        git add . 
        git push