---
- hosts: site03-access1
  gather_facts: false
  vars:
      root_path: /var/lib/ol-automation-manager/
  tasks:
  - name: push config file
    ios_config:
    src: "{{ root_path }}/backups_config/2022-12-12@05-07/site03-access1.config"