---
- name: restore router configurations
  hosts: site03
  gather_facts: false
  vars:
    root_path: /var/lib/ol-automation-manager/github
  tasks:
    - name: retreive configuration from backup-server to execution environment
      ansible.builtin.fetch:
        src: "{{ root_path }}/backups_config/{{rollback_date}}/{{inventory_hostname}}.txt"
        dest: "/tmp/{{rollback_date}}/"
        flat: true
      delegate_to: backup-server
      when: ansible_network_os is defined

    - name: load restore role
      include_role:
        name: "../roles/restore"
      when: ansible_network_os is defined
